In [1]:
from datetime import date

import pandas as pd
from IPython.display import Markdown

from data import PROGRAMS
from models import AVAILABILITY_TYPES, COUNTRIES, Semester

In [2]:
display(Markdown(f"## This notebook is run on {date.today()}"))

## This notebook is run on 2026-06-20

In [3]:
TARGET_SEMESTER = Semester(starting_year="2026", season="winter")

In [4]:
programs = pd.DataFrame(
    [
        {
            "name": p.name,
            "university": p.university_name,
            "country": p.country,
            "availability": p.get_availability(TARGET_SEMESTER),
            "application_fee": p.application_fee,
            "window_start": p.get_days_until_window_starts(TARGET_SEMESTER),
            "window_end": p.get_days_until_window_ends(TARGET_SEMESTER),
            "specializations": p.specializations,
        }
        for p in PROGRAMS
    ]
)

In [5]:
for a in AVAILABILITY_TYPES:
    display(Markdown(f"## {a.upper()}"))
    display(programs[programs["availability"] == a])

## CLOSED

,name,university,country,availability,application_fee,window_start,window_end,specializations
0,Computer Science,University of Stuttgart,Germany,closed,0.0,-217.0,-156,"[Autonomous Systems in Computer Science, Servi..."
2,Computer Science,University of Siegen,Germany,closed,0.0,-170.0,-51,"[Complex and Intelligent Software Systems, Emb..."
3,Computer Science,University of Bonn,Germany,closed,0.0,-66.0,-50,"[Algorithmics, Graphics/Vision/Audio, Informat..."
4,Computer Science,University of Hannover,Germany,closed,30.0,-66.0,-20,"[Data Science, Human Centered Computing, Syste..."
5,Computer Science,Karlsruhe Institute of Technology,Germany,closed,NaN,NaN,-5,"[Algorithm Engineering, Computer Graphics and ..."
6,Computer Science,University of Regensburg,Germany,closed,30.0,-66.0,-19,"[Bioinformatics, Core Computer Science, Human-..."
7,Computer Science,Ruhr University Bochum,Germany,closed,NaN,-231.0,-187,"[Artificial Intelligence, Cybersecurity, Quant..."
8,Computer Science,Paderborn University,Germany,closed,30.0,NaN,-20,"[Classical and Quantum Algorithm Design, Compu..."
10,Computer Science,University of Freiburg,Germany,closed,0.0,-66.0,-20,"[Artificial Intelligence, Cyber-Physical Systems]"
11,Computer Science International,University of Rostock,Germany,closed,30.0,-80.0,-20,"[Complex Systems, Information Systems]"
12,Computer Science,University of Potsdam,Germany,closed,0.0,-80.0,-19,"[Algorithms and Foundations, Data and AI, Digi..."
13,Computer Science,Saarland University,Germany,closed,NaN,NaN,-36,"[Cryptography, Distributed Information and Com..."
14,Computer and Information Science,University of Konstanz,Germany,closed,NaN,-94.0,-66,"[Algorithmics, Data science, Interactive syste..."
15,Applied Computer Science,University of Goettingen,Germany,closed,0.0,-97.0,-66,"[Applied System Engineering, Bioinformatics, B..."
16,Web and Data Science,University of Koblenz,Germany,closed,30.0,NaN,-5,"[Data Science, Engineering Web and Data-intens..."
17,Software Systems Engineering,RWTH Aachen University,Germany,closed,0.0,-201.0,-111,"[Applied Computer Science, Communication, Data..."
22,Cognitive Science,University of Osnabrueck,Germany,closed,30.0,-44.0,-5,"[Cognition: (Computational) Neuroscience, Cogn..."
23,Cognitive Science,Rhineland-Palatinate Technical University of K...,Germany,closed,60.0,-117.0,-51,"[Cognition and Knowledge, Cognitive Neuroscien..."
24,Cognitive Science,University of Potsdam,Germany,closed,0.0,-80.0,-19,"[Advanced Natural Language Processing, Cogniti..."
25,Cognitive Science,Technical University of Darmstadt,Germany,closed,NaN,-201.0,-111,"[Applied Cognitive Science, Artificial Intelli..."
26,Cognitive Systems,University of Ulm,Germany,closed,30.0,-80.0,-36,"[Interaction, Learning and Memory, Methods, Ge..."
27,"Mind, Brain and Behavior",University of Giessen,Germany,closed,30.0,-201.0,-5,"[Current Topics in Cognition and Development, ..."
28,Neural and Behavioural Sciences,University of Tuebingen,Germany,closed,NaN,NaN,-81,"[Brain Imaging and Recording, Cognitive Neuros..."
29,Neuroscience,University of Oldenburg,Germany,closed,30.0,-97.0,-51,"[Behavioural Neuroscience, Computational Neuro..."
30,Neuroscience,University of Bremen,Germany,closed,NaN,-111.0,-51,"[Computational Neuroscience, Experimental Neur..."
31,Cognitive Science,University of Trento,Italy,closed,30.0,-131.0,-22,"[Cognitive Neuroscience, Computational and The..."
32,Computer Science,University of Bari Aldo Moro,Italy,closed,NaN,NaN,-112,"[Artificial Intelligence, Security Engineering]"
33,Computer Science,University of Camerino,Italy,closed,20.0,NaN,-81,"[Artificial Intelligence, Business Information..."
34,Computer Science,University of Genoa,Italy,closed,30.0,-206.0,-92,"[Data Science & Engineering, Software Security..."
35,Computer Science and Engineering,Politecnico di Milano,Italy,closed,NaN,-158.0,-114,"[Ambient and data intelligence, Artificial int..."
36,Engineering in Computer Science,University of Messina,Italy,closed,30.0,-68.0,-41,None
37,Computer Science,University of Padua,Italy,closed,60.0,-110.0,-49,None
38,Computer Science,University of Pisa,Italy,closed,30.0,-201.0,-135,"[Artificial Intelligence, Big Data Technologie..."
39,Computer Science,Sapienza University of Rome,Italy,closed,30.0,-180.0,-36,None
40,Computer Science,University of Trento,Italy,closed,30.0,NaN,-108,"[Computer Science and Technologies, ICT Innova..."
41,Software Engineering,Free University of Bozen-Bolzano,Italy,closed,50.0,-110.0,-53,None

## NOT-OPENED

Empty DataFrame
Columns: [name, university, country, availability, application_fee, window_start, window_end, specializations]
Index: []

## OPENED

,name,university,country,availability,application_fee,window_start,window_end,specializations
1,Computer Science,Technical University of Hamburg,Germany,opened,0.0,-19.0,25,"[Computer and Software Engineering, Intelligen..."
9,Computer Science,University of Marburg,Germany,opened,30.0,-50.0,10,"[Artificial Intelligence, Cloud Computing, Dat..."
18,International Software Systems Science,Bamberg University,Germany,opened,0.0,-36.0,25,"[Communication Systems and Protocols, Distribu..."
19,Software Engineering,University of Hildesheim,Germany,opened,30.0,-66.0,10,"[Advanced Web Development, Model-Based Softwar..."
20,Web Engineering,Chemnitz University of Technology,Germany,opened,30.0,-80.0,25,"[Databases, Information Systems, Internet and ..."
21,Cognitive Science,Ruhr University Bochum,Germany,opened,NaN,-19.0,25,"[Brain and Behavior, Computation and Artificia..."

## NOT-CLOSED

Empty DataFrame
Columns: [name, university, country, availability, application_fee, window_start, window_end, specializations]
Index: []

In [6]:
display(Markdown("## Applicable Programs Sorted by Days until Window Closes"))

for country in COUNTRIES:
    display(Markdown(f"### {country}"))
    with pd.option_context("display.max_colwidth", None):
        display(
            programs[(programs["window_end"] >= 0) & (programs["country"] == country)]
            .assign(
                specializations=lambda d: d["specializations"].map(
                    lambda x: ", ".join(x) if isinstance(x, (list, tuple, set)) else x
                )
            )
            .sort_values(by=["window_end", "application_fee", "window_start"])
        )

# with pd.option_context("display.max_colwidth", None):
#     display(Markdown("## Applicable Programs' Specialiaztions"))
#     display(
#         programs[programs["window_end"] >= 0].assign(
#             specializations=lambda d: d["specializations"].map(
#                 lambda x: ", ".join(x) if isinstance(x, (list, tuple, set)) else x
#             )
#         )[["name", "university", "specializations"]]
#     )

## Applicable Programs Sorted by Days until Window Closes

### Germany

,name,university,country,availability,application_fee,window_start,window_end,specializations
19,Software Engineering,University of Hildesheim,Germany,opened,30.0,-66.0,10,"Advanced Web Development, Model-Based Software Engineering, Requirements Engineering for Quality, Software Architectures, Software Engineering, Software Product Line Engineering"
9,Computer Science,University of Marburg,Germany,opened,30.0,-50.0,10,"Artificial Intelligence, Cloud Computing, Databases, Distributed Systems, Graphics Programming, IT Security, Model Checking, Software Design"
18,International Software Systems Science,Bamberg University,Germany,opened,0.0,-36.0,25,"Communication Systems and Protocols, Distributed and Mobile Systems, Service-oriented Architectures, Software Analysis and Verification"
1,Computer Science,Technical University of Hamburg,Germany,opened,0.0,-19.0,25,"Computer and Software Engineering, Intelligence Engineering, Mathematics"
20,Web Engineering,Chemnitz University of Technology,Germany,opened,30.0,-80.0,25,"Databases, Information Systems, Internet and Web Technologies, Software Engineering"
21,Cognitive Science,Ruhr University Bochum,Germany,opened,NaN,-19.0,25,"Brain and Behavior, Computation and Artificial Intelligence, Mind and Language"

### Italy

Empty DataFrame
Columns: [name, university, country, availability, application_fee, window_start, window_end, specializations]
Index: []